[package]
name = "advent-of-code-2021"
version = "0.2.0"
authors = ["Clarence Leung <clarence.leung@mail.mcgill.ca>"]
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
